connector:
  name: Kiboko Magento Synchronizer
  jobs:
    kiboko_magento_driver_attribute_export:
      title: kiboko_magento_driver.jobs.magento_driver_attribute_export.title
      type:  export
      steps:
        attribute_export:
          title:       kiboko_magento_driver.jobs.magento_driver_attribute_export.title
          services:
            reader:    pim_connector.reader.doctrine.attribute
            processor: kiboko.magento_driver.processor.transformation.attribute
            writer:    kiboko.magento_driver.writer.doctrine.variant_group
          parameters:
            batch_size: 100