parameters:
  kiboko.magento_driver.persister.broker.class: Kiboko\Component\MagentoDriver\Broker\ProductAttributeValuePersisterBroker

services:
  kiboko.magento_driver.persister.broker:
    abstract: true
    class: '%kiboko.magento_driver.persister.broker%'