parameters:
  kiboko.magento_driver.deleter.attribute.class: Kiboko\Component\MagentoDriver\Deleter\Doctrine\AttributeDeleter
  kiboko.magento_driver.deleter.attribute_group.class: Kiboko\Component\MagentoDriver\Deleter\Doctrine\AttributeGroupDeleter
  kiboko.magento_driver.deleter.entity_store.class: Kiboko\Component\MagentoDriver\Deleter\Doctrine\EntityStoreDeleter
  kiboko.magento_driver.deleter.family.class: Kiboko\Component\MagentoDriver\Deleter\Doctrine\FamilyDeleter
  kiboko.magento_driver.deleter.product.class: Kiboko\Component\MagentoDriver\Deleter\Doctrine\ProductDeleter

services:
  kiboko.magento_driver.deleter.attribute:
    class: '%kiboko.magento_driver.deleter.attribute.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.attribute'

  kiboko.magento_driver.deleter.attribute_group:
    class: '%kiboko.magento_driver.deleter.attribute_group.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.attribute_group'

  kiboko.magento_driver.deleter.entity_store:
    class: '%kiboko.magento_driver.deleter.entity_store.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.entity_store'

  kiboko.magento_driver.deleter.family:
    class: '%kiboko.magento_driver.deleter.family.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.family'

  kiboko.magento_driver.deleter.product:
    class: '%kiboko.magento_driver.deleter.product.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.product'
