parameters:
  kiboko.magento_driver.mapper.entity_type.class: Kiboko\Component\MagentoMapper\Mapper\DefaultEntityTypeMapper
  kiboko.magento_driver.mapper.attribute.class: Kiboko\Component\MagentoMapper\Mapper\DefaultAttributeMapper

services:
  kiboko.magento_driver.mapper.entity_type:
    class: '%kiboko.magento_driver.mapper.entity_type.class%'

  kiboko.magento_driver.mapper.attribute:
    class: '%kiboko.magento_driver.mapper.attribute.class%'