parameters:
  kiboko.magento_driver.repository.doctrine.attribute.class:               Kiboko\Component\MagentoDriver\Repository\Doctrine\AttributeRepository
  kiboko.magento_driver.repository.doctrine.attribute_group.class:         Kiboko\Component\MagentoDriver\Repository\Doctrine\AttributeGroupRepository
  kiboko.magento_driver.repository.doctrine.catalog_attribute.class:       Kiboko\Component\MagentoDriver\Repository\Doctrine\CatalogAttributeRepository
  kiboko.magento_driver.repository.doctrine.entity_store.class:            Kiboko\Component\MagentoDriver\Repository\Doctrine\EntityStoreRepository
  kiboko.magento_driver.repository.doctrine.entity_type.class:             Kiboko\Component\MagentoDriver\Repository\Doctrine\EntityTypeRepository
  kiboko.magento_driver.repository.doctrine.family.class:                  Kiboko\Component\MagentoDriver\Repository\Doctrine\FamilyRepository
  kiboko.magento_driver.repository.doctrine.product_attribute_value.class: Kiboko\Component\MagentoDriver\Repository\Doctrine\ProuctAttributeValueRepository
  kiboko.magento_driver.repository.doctrine.product.class:                 Kiboko\Component\MagentoDriver\Repository\Doctrine\ProuctRepository

  kiboko.magento_driver.repository.cached.catalog_attribute.class: Kiboko\Component\MagentoDriver\Repository\CachedRepository\CachedProductAttributeRepository
  kiboko.magento_driver.repository.cached.family.class:            Kiboko\Component\MagentoDriver\Repository\CachedRepository\CachedFamilyRepository

services:
  kiboko.magento_driver.repository.doctrine.attribute:
    class: '%kiboko.magento_driver.repository.doctrine.attribute.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.attribute_group'

  kiboko.magento_driver.repository.doctrine.attribute_group:
    class: '%kiboko.magento_driver.repository.doctrine.attribute_group.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.attribute_group'

  kiboko.magento_driver.repository.doctrine.catalog_attribute:
    class: '%kiboko.magento_driver.repository.doctrine.catalog_attribute.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.product_attribute'

  kiboko.magento_driver.repository.doctrine.entity_store:
    class: '%kiboko.magento_driver.repository.doctrine.entity_store.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.entity_store'

  kiboko.magento_driver.repository.doctrine.entity_type:
    class: '%kiboko.magento_driver.repository.doctrine.entity_type.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.entity_type'

  kiboko.magento_driver.repository.doctrine.family:
    class: '%kiboko.magento_driver.repository.doctrine.family.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.family'

  kiboko.magento_driver.repository.doctrine.product_attribute_value:
    class: '%kiboko.magento_driver.repository.doctrine.product_attribute_value.class%'
    abstract: true

  kiboko.magento_driver.repository.doctrine.product_attribute_value.decimal:
    parent: 'kiboko.magento_driver.repository.doctrine.product_attribute_value'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.product_attribute_value.decimal'
      - '@kiboko.magento_driver.repository.doctrine.attribute'
      - '@kiboko.magento_driver.factory.product_attribute_value.facade'

  kiboko.magento_driver.repository.doctrine.product:
    class: '%kiboko.magento_driver.repository.doctrine.product.class%'
    arguments:
      - '@database.connection'
      - '@kiboko.magento_driver.query_builder.product'

  kiboko.magento_driver.repository.cached.catalog_attribute:
    class: '%kiboko.magento_driver.repository.cached.catalog_attribute.class%'
    arguments:
      - '@kiboko.magento_driver.repository.doctrine.catalog_attribute.class'

  kiboko.magento_driver.repository.cached.family:
    class: '%kiboko.magento_driver.repository.cached.family.class%'
    arguments:
      - '@kiboko.magento_driver.repository.doctrine.family.class'

