parameters:
  kiboko.magento_driver.writer.database.local_data_infile.class:  Kiboko\Component\MagentoDriver\Writer\Database\LocalDataInfileDatabaseWriter
  kiboko.magento_driver.writer.database.remote_data_infile.class: Kiboko\Component\MagentoDriver\Writer\Database\DataInfileDatabaseWriter
  kiboko.magento_driver.writer.database.temporary_writer.class:   Kiboko\Component\MagentoDriver\Writer\Database\DataInfileDatabaseWriter
  kiboko.magento_driver.writer.database.file_mover.class:         Kiboko\Component\MagentoDriver\Writer\Temporary\StandardTemporaryWriter

services:
  kiboko.magento_driver.writer.database.local_data_infile:
    class: '%kiboko.magento_driver.writer.database.local_data_infile.class%'
    arguments:
      - '@database.connection'
      - '@filesystem.driver'

  kiboko.magento_driver.writer.database.remote_data_infile:
    class: '%kiboko.magento_driver.writer.database.remote_data_infile.class%'
    arguments:
      - '@database.connection'
      - '@filesystem.driver'

  kiboko.magento_driver.writer.database.file_mover:
    class: '%kiboko.magento_driver.writer.database.file_mover.class%'

  kiboko.magento_driver.writer.database.file_mover:
    class: '%kiboko.magento_driver.writer.database.file_mover.class%'