<?php

namespace Kiboko\Component\MagentoMapper\Mapper\InMemory;

use Kiboko\Component\MagentoMapper\Mapper\AttributeMapperInterface;

class AttributeMapper implements AttributeMapperInterface
{
    use InMemoryMapperTrait;

    protected $mapping = [
        'additional_colors' => 169,
        'additional_materials' => 215,
        'ankle_size_metric' => 207,
        'belt_size_cm' => 223,
        'blade_width_metric' => 201,
        'brand' => 218,
        'calf_size_metric' => 206,
        'category_ids' => 108,
        'chest_size_eu' => 179,
        'chest_size_fr_es' => 178,
        'chest_size_metric' => 195,
        'chest_size_us_uk' => 180,
        'chocolate_box_size' => 222,
        'color' => 92,
        'cost' => 79,
        'country_of_manufacture' => 117,
        'created_at' => 115,
        'cuff_size_metric' => 203,
        'cup_size_eu' => 176,
        'cup_size_us' => 177,
        'customs_tax' => 166,
        'custom_design' => 103,
        'custom_design_from' => 104,
        'custom_design_to' => 105,
        'custom_layout_update' => 106,
        'description' => 72,
        'dress_skirt_size_central_eu' => 189,
        'dress_skirt_size_it' => 190,
        'dress_skirt_size_uk' => 191,
        'dress_skirt_size_us' => 187,
        'dress_skirt_size_western_eu' => 188,
        'ean13' => 160,
        'external_sku' => 161,
        'gallery' => 95,
        'gift_message_available' => 122,
        'group_price' => 90,
        'has_options' => 111,
        'heel_height_metric' => 209,
        'height_metric' => 212,
        'hips_size_eu' => 184,
        'hips_size_fr' => 182,
        'hips_size_fr_flat' => 181,
        'hips_size_metric' => 197,
        'hips_size_us' => 183,
        'image' => 85,
        'image_label' => 112,
        'inseam_height_metric' => 198,
        'inside_pockets' => 171,
        'is_recurring' => 100,
        'length_metric' => 211,
        'links_exist' => 131,
        'links_purchased_separately' => 128,
        'links_title' => 130,
        'main_color' => 226,
        'main_size_iso' => 170,
        'manufacturer' => 81,
        'material' => 214,
        'media_gallery' => 88,
        'meta_description' => 84,
        'meta_keyword' => 83,
        'meta_keywords' => 163,
        'meta_name' => 162,
        'meta_title' => 82,
        'minimal_price' => 99,
        'minimal_public_price' => 165,
        'msrp' => 120,
        'msrp_display_actual_price_type' => 119,
        'msrp_enabled' => 118,
        'name' => 71,
        'neck_size_metric' => 208,
        'news_from_date' => 93,
        'news_to_date' => 94,
        'old_id' => 89,
        'options_container' => 109,
        'original_description' => 217,
        'original_name' => 216,
        'original_price' => 219,
        'outseam_height_metric' => 199,
        'outside_pockets' => 172,
        'page_layout' => 107,
        'price' => 75,
        'price_type' => 123,
        'price_view' => 126,
        'recurring_profile' => 101,
        'release_date' => 167,
        'required_options' => 110,
        'ribbon' => 156,
        'samples_title' => 129,
        'shipment_type' => 127,
        'shirt_size_eu' => 185,
        'shirt_size_us' => 186,
        'shoe_size_eu' => 192,
        'shoe_size_uk' => 193,
        'shoe_size_us' => 194,
        'short_description' => 73,
        'shoulder_width_metric' => 200,
        'skirt_length_metric' => 204,
        'sku' => 74,
        'sku_type' => 124,
        'sleeve_size_metric' => 202,
        'small_image' => 86,
        'small_image_label' => 113,
        'special_from_date' => 77,
        'special_price' => 76,
        'special_to_date' => 78,
        'status' => 96,
        'stock' => 164,
        'supplier_colors' => 220,
        'supplier_materials' => 221,
        'tax_class_id' => 121,
        'thigh_size_metric' => 205,
        'thumbnail' => 87,
        'thumbnail_label' => 114,
        'tier_price' => 91,
        'top_size_fr' => 173,
        'top_size_us_men' => 174,
        'top_size_us_women' => 175,
        'updated_at' => 116,
        'url_key' => 97,
        'url_path' => 98,
        'visibility' => 102,
        'waist_size_metric' => 196,
        'weight' => 80,
        'weight_metric' => 213,
        'weight_type' => 125,
        'width_metric' => 210,
    ];

    /**
     * @param array $mapping
     */
    public function __construct(
        array $mapping
    ) {
        $this->mapping = $mapping;
    }
}
